### ISSUE TITLE
Limitar a largura dos textos das vagas.

### ISSUE THREAD

**Issue by lazaroalvarenga** [remotejobbr/jobs#1]
Acredito que fique mais confortável se o contentContainer tivesse uma largura limitadora. Eu por ex, to acessando num monitor full hd 24'' e fica bem estranho ler uma linha do início ao fim do monitor.

p.s. que projeto iraaado!

**Comment by IsTheJack** [comment]
Excelente @lazaroalvarenga! :D Muito obrigado pelo feedback... Estou entrando em contato com um amigo Ux designer pra contribuir no projeto, então ele vai mudar e evoluir bastante nesse sentido de design e usabilidade... Mas fique à vontade para continuar contribuindo com ideias e sugestões. <3

**Comment by lazaroalvarenga** [comment]
Massa! Se precisar/aceitar PR's para contribuir com essa evolução é só falar =)

**Comment by IsTheJack** [comment]
@lazaroalvarenga Todo PR é bem vindo. A ideia é exatamente essa mesma...

**Comment by IsTheJack** [comment]
Resolvido com o PR (#2 )
